### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by han44-illinois**
Minor formatting edit in the example, as the existing format does not work.

### CODE REVIEW

**Comment by mmseng** [comment]
Did you try this directly via powershell? Technically the existing format should work (and has worked for me) as it will be interpreted by Powershell as an array of strings. But the edit should not work, and Powershell will consider it one long string (i.e. one long NetID in this case). My guess is MECM (where the script is modified compared to this repo's version) is just interpreting string arrays and/or quotation escaping in a slightly different and/or incorrect manner.

**Comment by han44-illinois** [comment]
Yep - I tried this directly via powershell after ditching MECM due to the string length limit.

When using the string array formatting, I receive the following error:
```
Remove-LocalUserProfiles : Cannot process argument transformation on parameter 'ExcludeUsers'. Cannot convert value to
type System.String.
At line:1 char:83
+ ... filesOlderThan 1 -TimeoutMins 55 -ExcludeUsers $excludeusers2 -log C: ...
+                                                    ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Remove-LocalUserProfiles], ParameterBindingArgumentTransformationExcep
   tion
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Remove-LocalUserProfiles
 ```

In this case $excludeusers2 was a variable I used to store said string array. Switching it from that to a single string with commas works, though.

**Comment by mmseng** [comment]
Ah, my mistake. I thought I implemented `-ExludeUsers` as a string array (which is what I usually do), but I actually implemented it as a string and manually split it later in the code. I must have forgotten this when I wrote the readme.

**Comment by mmseng** [comment]
P.S. I also updated the parameter documentation and language to reflect the change better (https://github.com/engrit-illinois/Remove-LocalUserProfiles/commit/6819a6584ab4b37aa6bfe6adc52ae2437d9aa63b)

**Pull request merged**
